[world]
name = "Tournament"
description = "Tournament component used to create and compete in tournaments across Dojo games."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "tournaments"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "budokan_v_1_0_4"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x02f808e319783173b7a36bae6ab318fb98f6553fce73786b430cc02110483fd4"  # Uncomment and update this line with your world address.

[writers]
# Tournament
"budokan_v_1_0_4-Tournament" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-Registration" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-Leaderboard" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-PlatformMetrics" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-TournamentTokenMetrics" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-PrizeMetrics" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-EntryCount" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-Prize" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-Token" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-TournamentConfig" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-PrizeClaim" = ["budokan_v_1_0_4-tournament_mock"]
"budokan_v_1_0_4-QualificationEntries" = ["budokan_v_1_0_4-tournament_mock"]
# Game
"budokan_v_1_0_4-GameMetadata" = ["budokan_v_1_0_4-game_mock"]
"budokan_v_1_0_4-GameCounter" = ["budokan_v_1_0_4-game_mock"]
"budokan_v_1_0_4-SettingsDetails" = ["budokan_v_1_0_4-game_mock"]
"budokan_v_1_0_4-SettingsCounter" = ["budokan_v_1_0_4-game_mock"]
"budokan_v_1_0_4-Settings" = ["budokan_v_1_0_4-game_mock"]
"budokan_v_1_0_4-TokenMetadata" = ["budokan_v_1_0_4-game_mock"]
"budokan_v_1_0_4-Score" = ["budokan_v_1_0_4-game_mock"]


[migration]
order_inits = []
skip_contracts = ["budokan_v_1_0_4-Budokan"]
