# Realms World
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]
index_pending = true
world_block = 1237265 # dark shuffle deployment block
contracts = [
  "ERC721:0x0320f977f47f0885e376b781d9e244d9f59f10154ce844ae1815c919f0374726", # dark shuffle
]

[events]
raw = true