# Realms World
world_address = "0x01bfa92665fb815c9ec5f37c562a5c9a06fdf23ce022c1d33d4ac07cef5ad80c"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
events_chunk_size = 1024 # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit
index_pending = true # Enable indexing pending blocks
polling_interval = 500 # Polling interval in milliseconds
max_concurrent_tasks = 100 # Maximum concurrent indexing tasks
index_transactions = true
contracts = [
  "ERC721:0x4359aee29873cd9603207d29b4140468bac3e042aa10daab2e1a8b2dd60ef7b", # dark shuffle
]

[events]
raw = true